server:
  port: 9090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 5
      
dojo:
  message: Hello again!
  
management:
  security:
    enabled: false
    

    
spring:
  zipkin:
    baseUrl: http://localhost:9411
    enabled: true
  sleuth:
    sampler:
      percentage: 1.0